/**
 * What RoofersLabs sells, as data.
 *
 * This file is the entire definition of the commercial catalogue. The
 * provisioner reads it and makes the payment provider match: a plan that is
 * here and not at the provider gets created, and its generated id is persisted.
 * Adding a plan is an entry here plus a re-run of `billing:paypal:setup` — no
 * dashboard work, no environment variable, no code change anywhere else.
 *
 * Two rules keep that honest:
 *
 *  1. **No identifier appears here.** Provider ids are generated by the
 *     provider and persisted in `billing_catalog`. Hardcoding one would put the
 *     same value in two places and guarantee they eventually disagree.
 *  2. **`key` is permanent.** It is what the persisted row is looked up by, so
 *     changing one orphans the old row and provisions a duplicate. Prices,
 *     names and descriptions may change freely; keys may not.
 */
import { BillingInterval, SubscriptionPlan } from '@rooferslabs/shared';

/** The product every plan hangs off. PayPal requires one before any plan. */
export interface CatalogProduct {
  /** Stable lookup key. Also the suffix of the deterministic provider id. */
  key: string;
  name: string;
  description: string;
  /** PayPal's taxonomy. `SERVICE` is correct for software sold as a subscription. */
  type: 'SERVICE' | 'DIGITAL' | 'PHYSICAL';
  category: string;
}

/**
 * Which price a plan entry carries.
 *
 * `production` is what the product advertises and what a customer is meant to
 * pay. `test` is the same plan at a token amount, used to prove a live payment
 * pipeline end to end — real credentials, real webhook signatures, real money
 * moving into the bank — without taking a full subscription fee to do it.
 *
 * Exactly one mode is active per deployment, chosen by `PAYPAL_TEST_PRICING`.
 * Both are provisioned, because a flag that requires a plan to be created first
 * is not really a flag.
 */
export type PricingMode = 'production' | 'test';

export interface CatalogPlan {
  /** Stable lookup key. Never change it once provisioned. */
  key: string;
  /**
   * Which price this entry is. Two entries may share a plan/interval as long as
   * their modes differ — that pairing is the whole test-pricing mechanism.
   */
  pricingMode: PricingMode;
  /** Which domain plan this is, for entitlement and upgrade ordering. */
  plan: SubscriptionPlan;
  interval: BillingInterval;
  /** Shown to the customer on the provider's approval page. */
  name: string;
  description: string;
  /**
   * The recurring amount, as a decimal string.
   *
   * A string, not a number: `49.00` and `49` are the same money but different
   * floats, and money must never round-trip through a binary float on its way
   * to a payment provider.
   */
  amount: string;
  /** ISO 4217, uppercase. */
  currency: string;
  /**
   * Whether the subscription renews indefinitely. False would mean a fixed
   * number of cycles, which nothing here sells.
   */
  autoRenew: boolean;
  /**
   * Consecutive failed payments before the provider suspends the subscription.
   * Three is PayPal's own default and gives a customer with an expired card
   * roughly a month to notice.
   */
  paymentFailureThreshold: number;
}

export const CATALOG_PRODUCT: CatalogProduct = {
  key: 'r1-echo',
  name: 'r1 Echo',
  description: 'AI Voice Receptionist for Roofing Companies',
  type: 'SERVICE',
  category: 'SOFTWARE',
};

/**
 * The plans on sale.
 *
 * Only the Founding Customer monthly plan is sold today. Professional and the
 * annual intervals exist in the domain enums but are deliberately absent here:
 * an unprovisioned plan makes `priceIdFor` refuse a checkout, which is the
 * correct answer for something that is not for sale, and is far safer than a
 * plan quietly created at a price nobody agreed.
 */
export const CATALOG_PLANS: readonly CatalogPlan[] = [
  {
    key: 'founding-monthly',
    pricingMode: 'production',
    plan: SubscriptionPlan.STARTER,
    interval: BillingInterval.MONTH,
    name: 'Founding Customer',
    description: 'r1 Echo — Founding Customer plan, billed monthly.',
    amount: '49.00',
    currency: 'USD',
    autoRenew: true,
    paymentFailureThreshold: 3,
  },
  {
    /**
     * The same plan at a token price, for proving a live pipeline.
     *
     * Provisioned alongside the real one and completely inert until
     * `PAYPAL_TEST_PRICING=true`. It is a *separate PayPal plan*, never an edit
     * to the production one — PayPal cannot reprice a plan that has live
     * subscriptions, and the $49 plan must stay exactly as it is.
     *
     * The name is deliberately explicit. It is the one piece of this that a
     * customer can see: PayPal shows the plan name on its approval page, and
     * somebody paying $1 should be able to tell that is not the normal price.
     */
    key: 'founding-monthly-test',
    pricingMode: 'test',
    plan: SubscriptionPlan.STARTER,
    interval: BillingInterval.MONTH,
    name: 'Founding Customer (test pricing)',
    description: 'r1 Echo — Founding Customer plan at test pricing. Not the published price.',
    amount: '1.00',
    currency: 'USD',
    autoRenew: true,
    paymentFailureThreshold: 3,
  },
];

/**
 * The catalogue key for a plan/interval/mode triple, as stored in
 * `billing_catalog`.
 *
 * The mode is part of the key, which is what lets the production and test
 * prices for the same plan coexist as two rows and two PayPal plans. The
 * production key is unsuffixed so it is unchanged from before test pricing
 * existed — rows already provisioned keep working without a migration.
 */
export function planCatalogKey(
  plan: SubscriptionPlan,
  interval: BillingInterval,
  mode: PricingMode = 'production',
): string {
  return mode === 'test' ? `plan:${plan}:${interval}:test` : `plan:${plan}:${interval}`;
}

/** The catalogue key for the product. */
export const PRODUCT_CATALOG_KEY = 'product';

/** The catalogue key for the registered webhook. */
export const WEBHOOK_CATALOG_KEY = 'webhook';

/**
 * The events the webhook must be subscribed to.
 *
 * Exactly the set `PayPalProvider.verifyAndParseWebhook` acts on. Subscribing to
 * more would mean paying to verify deliveries that are then discarded as
 * ignored; subscribing to fewer would silently drop a state change, which is the
 * failure this list exists to prevent — so the provisioner reconciles the
 * registered webhook against it rather than assuming.
 */
export const WEBHOOK_EVENT_TYPES: readonly string[] = [
  'BILLING.SUBSCRIPTION.CREATED',
  'BILLING.SUBSCRIPTION.ACTIVATED',
  'BILLING.SUBSCRIPTION.UPDATED',
  'BILLING.SUBSCRIPTION.CANCELLED',
  'BILLING.SUBSCRIPTION.SUSPENDED',
  'BILLING.SUBSCRIPTION.EXPIRED',
  'BILLING.SUBSCRIPTION.RE-ACTIVATED',
  'BILLING.SUBSCRIPTION.PAYMENT.FAILED',
  'PAYMENT.SALE.COMPLETED',
  'PAYMENT.SALE.DENIED',
  'PAYMENT.SALE.REFUNDED',
  'PAYMENT.SALE.REVERSED',
];

/**
 * A stable hash of what we asked the provider to create.
 *
 * Stored alongside the id so the provisioner can tell "this already exists" from
 * "this exists but is not what the catalogue now describes". The second case is
 * reported rather than silently accepted: a plan's price cannot be edited at
 * PayPal once subscriptions exist against it, so the operator has to decide
 * whether to launch a new plan.
 */
export function fingerprintOf(value: Record<string, unknown>): string {
  // Sorted keys so an unrelated reordering of the object literal does not read
  // as a change to the catalogue.
  const canonical = JSON.stringify(value, Object.keys(value).sort());
  let hash = 0;
  for (let i = 0; i < canonical.length; i += 1) {
    hash = (Math.imul(31, hash) + canonical.charCodeAt(i)) | 0;
  }
  return `v1:${(hash >>> 0).toString(16)}`;
}

/** The fingerprint of a plan entry: everything the provider would bake in. */
export function planFingerprint(plan: CatalogPlan): string {
  return fingerprintOf({
    amount: plan.amount,
    currency: plan.currency,
    interval: plan.interval,
    autoRenew: plan.autoRenew,
    paymentFailureThreshold: plan.paymentFailureThreshold,
  });
}

/** The fingerprint of the product entry. */
export function productFingerprint(product: CatalogProduct): string {
  return fingerprintOf({
    name: product.name,
    description: product.description,
    type: product.type,
    category: product.category,
  });
}
