/** @type {import('tailwindcss').Config} */
// Utilities map onto the design tokens in src/styles/tokens.css. Prefer the
// semantic names (bg-surface, text-ink, border-line, bg-accent, text-emergency)
// so light/dark theming and re-brands flow from the tokens, never hardcoded.
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        // Primitive terracotta/clay scale — also re-themes legacy `brand-*`.
        brand: {
          50: 'var(--clay-50)',
          100: 'var(--clay-100)',
          200: 'var(--clay-200)',
          300: 'var(--clay-300)',
          400: 'var(--clay-400)',
          500: 'var(--clay-500)',
          600: 'var(--clay-600)',
          700: 'var(--clay-700)',
          800: 'var(--clay-800)',
          900: 'var(--clay-900)',
        },
        clay: {
          50: 'var(--clay-50)',
          100: 'var(--clay-100)',
          200: 'var(--clay-200)',
          300: 'var(--clay-300)',
          400: 'var(--clay-400)',
          500: 'var(--clay-500)',
          600: 'var(--clay-600)',
          700: 'var(--clay-700)',
          800: 'var(--clay-800)',
          900: 'var(--clay-900)',
        },
        // Transitional: warm-tinted neutrals (hue ~55) so legacy `slate-*`
        // reads warm/on-brand. New code should use ink/surface/line instead.
        slate: {
          50: 'oklch(0.985 0.003 55)',
          100: 'oklch(0.97 0.004 55)',
          200: 'oklch(0.93 0.005 55)',
          300: 'oklch(0.87 0.006 55)',
          400: 'oklch(0.72 0.008 55)',
          500: 'oklch(0.58 0.009 55)',
          600: 'oklch(0.46 0.008 55)',
          700: 'oklch(0.37 0.008 55)',
          800: 'oklch(0.27 0.006 55)',
          900: 'oklch(0.19 0.005 55)',
          950: 'oklch(0.14 0.005 55)',
        },
        // Theme-aware semantic surfaces & text.
        canvas: 'var(--bg-canvas)',
        base: 'var(--bg-base)',
        surface: {
          DEFAULT: 'var(--surface-1)',
          1: 'var(--surface-1)',
          2: 'var(--surface-2)',
          3: 'var(--surface-3)',
          overlay: 'var(--surface-overlay)',
        },
        line: {
          subtle: 'var(--border-subtle)',
          DEFAULT: 'var(--border-default)',
          strong: 'var(--border-strong)',
        },
        ink: {
          DEFAULT: 'var(--text-primary)',
          muted: 'var(--text-secondary)',
          faint: 'var(--text-tertiary)',
          disabled: 'var(--text-disabled)',
          'on-brand': 'var(--text-on-primary)',
          'on-emergency': 'var(--text-on-emergency)',
        },
        accent: {
          DEFAULT: 'var(--color-primary)',
          hover: 'var(--color-primary-hover)',
          active: 'var(--color-primary-active)',
          subtle: 'var(--color-primary-subtle)',
          border: 'var(--color-primary-border)',
        },
        secondary: {
          DEFAULT: 'var(--color-secondary)',
          hover: 'var(--color-secondary-hover)',
          active: 'var(--color-secondary-active)',
          subtle: 'var(--color-secondary-subtle)',
        },
        emergency: {
          DEFAULT: 'var(--color-emergency)',
          hover: 'var(--color-emergency-hover)',
          active: 'var(--color-emergency-active)',
          subtle: 'var(--color-emergency-subtle)',
          border: 'var(--color-emergency-border)',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
          subtle: 'var(--color-warning-subtle)',
          border: 'var(--color-warning-border)',
        },
        success: {
          DEFAULT: 'var(--color-success)',
          subtle: 'var(--color-success-subtle)',
          border: 'var(--color-success-border)',
        },
        info: {
          DEFAULT: 'var(--color-info)',
          subtle: 'var(--color-info-subtle)',
          border: 'var(--color-info-border)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SF Mono', 'Menlo', 'monospace'],
      },
      fontSize: {
        display: ['4.5rem', { lineHeight: '1.04', letterSpacing: '-0.02em', fontWeight: '700' }],
        hero: ['3.5rem', { lineHeight: '1.08', letterSpacing: '-0.02em', fontWeight: '700' }],
        h1: ['2.5rem', { lineHeight: '1.15', letterSpacing: '-0.015em', fontWeight: '700' }],
        h2: ['2rem', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['1.625rem', { lineHeight: '1.25', letterSpacing: '-0.005em', fontWeight: '600' }],
        h4: ['1.3125rem', { lineHeight: '1.3', fontWeight: '600' }],
        h5: ['1.0625rem', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6' }],
        body: ['0.9375rem', { lineHeight: '1.6' }],
        small: ['0.8125rem', { lineHeight: '1.5' }],
        caption: ['0.75rem', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        label: ['0.8125rem', { lineHeight: '1.3', letterSpacing: '0.01em', fontWeight: '600' }],
        metric: ['2rem', { lineHeight: '1.1', fontWeight: '600' }],
        'table-header': [
          '0.75rem',
          { lineHeight: '1.2', letterSpacing: '0.03em', fontWeight: '600' },
        ],
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        card: 'var(--elevation-card)',
        'card-hover': 'var(--elevation-card-hover)',
        nav: 'var(--elevation-nav)',
        dropdown: 'var(--elevation-dropdown)',
        dialog: 'var(--elevation-dialog)',
        tooltip: 'var(--elevation-tooltip)',
        button: 'var(--elevation-button)',
      },
      ringColor: {
        focus: 'var(--focus-ring)',
      },
      maxWidth: {
        narrow: 'var(--container-narrow)',
        marketing: 'var(--container-marketing)',
        dashboard: 'var(--container-dashboard)',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
        decelerate: 'var(--ease-decelerate)',
        accelerate: 'var(--ease-accelerate)',
        spring: 'var(--ease-spring)',
      },
      transitionDuration: {
        instant: '100ms',
        fast: '150ms',
        base: '200ms',
        slow: '300ms',
        slower: '450ms',
      },
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'scale-in': {
          from: { opacity: '0', transform: 'translateY(4px) scale(0.98)' },
          to: { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
      },
      animation: {
        'fade-in': 'fade-in var(--duration-base) var(--ease-standard)',
        'scale-in': 'scale-in var(--duration-base) var(--ease-decelerate)',
      },
    },
  },
  plugins: [],
};
