-- Early-access requests captured from the pre-launch launch page.
--
-- Purely additive: one new table, no column touched on any existing one, so
-- this cannot affect a running deployment mid-rollout. Written by hand rather
-- than generated — `prisma migrate diff` is not used in this project because it
-- renders renames as data-destroying DROP + ADD pairs.
--
-- `id` is TEXT because ids are cuid()s generated by the Prisma client, not by
-- the database.

CREATE TABLE "early_access_requests" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "company" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT,
    "referrer" TEXT,
    "userAgent" TEXT,
    "contactedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "early_access_requests_pkey" PRIMARY KEY ("id")
);

-- Lookup by address when following a lead up. Deliberately NOT unique: the same
-- person submitting twice is ordinary behaviour on a public form, and a unique
-- constraint would turn that into a 500 on an unauthenticated endpoint.
CREATE INDEX "early_access_requests_email_idx" ON "early_access_requests"("email");

-- The list is read newest-first.
CREATE INDEX "early_access_requests_createdAt_idx" ON "early_access_requests"("createdAt");
