#!/usr/bin/env bash
# =============================================================================
# RoofersLabs — local development setup
# =============================================================================
# The one command between a fresh clone and a working environment:
#
#   bun run setup
#
# Idempotent. Safe to re-run at any time — it never overwrites an existing .env
# and never destroys data.
#
# Touches NO AWS resources. It reads no Terraform state, needs no credentials,
# and works offline once the Docker images are pulled. That is deliberate: the
# previous version of this workflow resolved its configuration from
# `terraform output` against an environment that had never been applied, so a
# clean clone could not start at all.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

GREEN=$'\033[32m'; RED=$'\033[31m'; YELLOW=$'\033[33m'; DIM=$'\033[2m'; BOLD=$'\033[1m'; RESET=$'\033[0m'

step() { printf '\n%s==>%s %s\n' "$BOLD" "$RESET" "$1"; }
ok()   { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
info() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }

# Every failure exits here, with what to do rather than where it happened.
die() {
  printf '\n%serror:%s %s\n\n' "$RED" "$RESET" "$1" >&2
  [ $# -gt 1 ] && printf '%s\n\n' "$2" >&2
  exit 1
}

# ---- 1. Tooling ---------------------------------------------------------------

step "Checking tooling"

if command -v bun >/dev/null 2>&1; then
  ok "bun $(bun --version)"
  PKG="bun"
elif command -v npm >/dev/null 2>&1; then
  # Bun is what the docs assume, but nothing here actually requires it, and
  # refusing to set up a working checkout over a package manager preference
  # would be obstructive.
  printf '  %s!%s bun not found — falling back to npm\n' "$YELLOW" "$RESET"
  info "install bun for faster installs: curl -fsSL https://bun.sh/install | bash"
  PKG="npm"
else
  die "Neither bun nor npm is installed." \
"Install bun:

    curl -fsSL https://bun.sh/install | bash"
fi

command -v node >/dev/null 2>&1 || die "Node.js is not installed." \
"Install Node 22 or newer: https://nodejs.org"

NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
if [ "$NODE_MAJOR" -lt 22 ]; then
  die "Node $(node -v) is too old — this project needs Node 22 or newer." \
"With nvm:

    nvm install 22 && nvm use 22"
fi
ok "node $(node -v)"

command -v docker >/dev/null 2>&1 || die "Docker is not installed." \
"Docker runs the local Postgres and Redis. Install Docker Desktop:
https://www.docker.com/products/docker-desktop"

docker info >/dev/null 2>&1 || die "Docker is installed but not running." \
"Start Docker Desktop, wait for it to report Running, then re-run:

    bun run setup"
ok "docker $(docker --version | sed 's/Docker version //; s/,.*//')"

# The AWS CLI is deliberately NOT required. Local development uses Docker
# Postgres and Docker Redis and reads no AWS secret, so demanding it would be a
# prerequisite that buys nothing.
if command -v aws >/dev/null 2>&1; then
  info "aws cli present — not required for local development"
fi

# ---- 2. Environment file ------------------------------------------------------

step "Environment configuration"

if [ -f .env ]; then
  ok ".env exists (left untouched)"
else
  cp .env.example .env
  ok "created .env from .env.example"
  printf '\n  %sBefore continuing, add your Clerk DEVELOPMENT keys to .env:%s\n' "$BOLD" "$RESET"
  info "  Clerk Dashboard → instance selector → Development → API Keys"
  info "  CLERK_PUBLISHABLE_KEY=pk_test_...   CLERK_SECRET_KEY=sk_test_..."
  printf '\n  Then re-run: %sbun run setup%s\n\n' "$BOLD" "$RESET"
  exit 0
fi

if [ -f apps/web/.env.local ]; then
  ok "apps/web/.env.local exists (left untouched)"
else
  # The web dev server needs the same publishable key. Derived from .env rather
  # than asked for twice, so the two cannot drift.
  CLERK_PK="$(grep -E '^CLERK_PUBLISHABLE_KEY=' .env | head -1 | cut -d= -f2- | tr -d '"'"'"' ' || true)"
  cat > apps/web/.env.local <<EOF
# Generated by scripts/setup-dev.sh. Safe to edit; re-created only if deleted.
VITE_APP_ENV=development
VITE_APP_LAUNCH_MODE=public
# Empty: the Vite dev server proxies /v1 to http://localhost:4000.
VITE_API_BASE_URL=
VITE_CLERK_PUBLISHABLE_KEY=${CLERK_PK}
EOF
  ok "created apps/web/.env.local"
fi

# ---- 3. Dependencies ----------------------------------------------------------

step "Installing dependencies"
if [ "$PKG" = "bun" ]; then
  bun install
else
  npm install
fi
ok "dependencies installed"

# ---- 4. Data stores -----------------------------------------------------------

step "Starting Postgres and Redis"
docker compose -f docker/docker-compose.yml up -d postgres redis >/dev/null 2>&1 \
  || die "Could not start the Docker services." \
"Try it directly to see why:

    docker compose -f docker/docker-compose.yml up postgres redis"

# Compose returns as soon as the containers are created, which is well before
# Postgres is accepting connections — running migrations immediately fails with
# a connection error that looks like a configuration problem.
printf '  waiting for Postgres'
for i in $(seq 1 60); do
  if docker compose -f docker/docker-compose.yml exec -T postgres \
       pg_isready -U rooferslabs -d rooferslabs >/dev/null 2>&1; then
    printf '\r'; ok "Postgres accepting connections    "
    break
  fi
  printf '.'
  sleep 1
  [ "$i" -eq 60 ] && { printf '\n'; die "Postgres did not become ready within 60s." \
"Check the container logs:

    docker compose -f docker/docker-compose.yml logs postgres"; }
done
ok "Redis started"

# ---- 5. Prisma ----------------------------------------------------------------

step "Preparing the database"

# Generate first: `migrate deploy` needs the engines, and a stale client is the
# most common cause of a type error that has nothing to do with the code.
if [ "$PKG" = "bun" ]; then bun run prisma:generate >/dev/null; else npm run prisma:generate >/dev/null; fi
ok "Prisma client generated"

# `migrate deploy`, not `migrate dev`: deploy applies committed migrations and
# nothing else. `migrate dev` would offer to reset the database and can author a
# new migration from a drifted schema, neither of which belongs in a setup script.
if npx --prefix apps/api prisma migrate deploy --schema apps/api/prisma/schema.prisma >/dev/null 2>&1; then
  ok "migrations applied"
else
  die "Migrations failed to apply." \
"See the full error with:

    npx --prefix apps/api prisma migrate deploy --schema apps/api/prisma/schema.prisma

If the local database is in a state not worth untangling, reset it — this
destroys LOCAL data only:

    bun run db:reset"
fi

# ---- 6. Validate ---------------------------------------------------------------

step "Validating configuration"
if ! node scripts/check-dev-env.mjs; then
  die "Setup stopped: the configuration above is not usable yet." \
"Fix the problems listed, then re-run:

    bun run setup"
fi

# ---- Done ------------------------------------------------------------------------

cat <<EOF

${GREEN}${BOLD}Setup complete.${RESET}

  ${BOLD}bun run dev${RESET}          start the API and web app together
    ${DIM}api   http://localhost:4000${RESET}
    ${DIM}web   http://localhost:5173${RESET}

  ${BOLD}bun run db:reset${RESET}     wipe and rebuild the local database
  ${BOLD}bun run check${RESET}        re-run these checks

  ${DIM}docs/local-development.md${RESET}

EOF
